# Site settings
title : THIS IS B.L.O.G! 
email : masteryoh@naver.com
description: > # this means to ignore newlines until "baseurl:"
  
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/blog" # the subpath of your site, e.g. /blog/
url: "http://moonsu.github.io" # the base hostname & protocol for your site
twitter_username: null 
github_username:  Moonsu 

# Build settings
markdown: kramdown
